apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-snap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-ontap-nas
  resources:
    requests:
      storage: 2Gi
  dataSource:
    name: snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
