apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-snap-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-ontap-nas
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: snap-volume
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
