kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-qtree-san
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-ontap-san-economy
