apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-ontap-san
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  storagePools: "be-volume-san:.*"
allowVolumeExpansion: true
