apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: sc-ontap-nas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi