kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-volume-import
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-ontap-nas
