apiVersion: v1
kind: Pod
metadata:
  name: busybox-volume-clone 
  namespace: default
spec:
  volumes:
    - name: pvc-bb
      persistentVolumeClaim:
        claimName: pvc-from-snap-volume 
  containers:
  - image: busybox:1.28.4
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: pvc-bb
      mountPath: /tmp
  restartPolicy: Always
